const daysAgo = (days) => new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();

export const seedUsers = [
  {
    id: 'usr_admin',
    fullName: 'Ariana Wells',
    email: 'admin@controllusion.com',
    password: 'Admin@123',
    role: 'Admin',
    isActive: true,
    title: 'Head of Revenue Operations',
    phone: '+1 (202) 555-0148',
    themePreference: 'light',
    createdAt: daysAgo(220),
  },
  {
    id: 'usr_sara',
    fullName: 'Sara Kim',
    email: 'sara@controllusion.com',
    password: 'User@1234',
    role: 'User',
    isActive: true,
    title: 'Account Executive',
    phone: '+1 (202) 555-0120',
    themePreference: 'light',
    createdAt: daysAgo(180),
  },
  {
    id: 'usr_ethan',
    fullName: 'Ethan Cole',
    email: 'ethan@controllusion.com',
    password: 'User@1234',
    role: 'User',
    isActive: true,
    title: 'Customer Success Manager',
    phone: '+1 (202) 555-0172',
    themePreference: 'light',
    createdAt: daysAgo(165),
  },
  {
    id: 'usr_olivia',
    fullName: 'Olivia Hart',
    email: 'olivia@controllusion.com',
    password: 'User@1234',
    role: 'User',
    isActive: false,
    title: 'Sales Operations Analyst',
    phone: '+1 (202) 555-0113',
    themePreference: 'light',
    createdAt: daysAgo(120),
  },
];

export const seedCustomers = [
  {
    id: 'cus_101',
    fullName: 'Maya Patel',
    email: 'maya.patel@northforge.io',
    phone: '+1 (312) 555-0101',
    company: 'Northforge',
    jobTitle: 'Procurement Director',
    status: 'VIP',
    stage: 'Negotiation',
    dealValue: 42000,
    notes:
      'Evaluating a multi-team CRM rollout. Prioritizes onboarding speed, permissions, and reporting depth.',
    createdAt: daysAgo(5),
    lastContactedAt: daysAgo(1),
    ownerId: 'usr_sara',
    location: 'Chicago, IL',
    industry: 'Manufacturing',
    timeline: [
      {
        id: 'evt_101_1',
        type: 'Call',
        title: 'Executive discovery call',
        description: 'Reviewed current tool sprawl and mapped implementation requirements.',
        date: daysAgo(4),
      },
      {
        id: 'evt_101_2',
        type: 'Email',
        title: 'Sent pricing proposal',
        description: 'Shared seat-based proposal and onboarding timeline.',
        date: daysAgo(2),
      },
      {
        id: 'evt_101_3',
        type: 'Meeting',
        title: 'Security review scheduled',
        description: 'Technical buyer requested SSO, audit log, and export policy details.',
        date: daysAgo(1),
      },
    ],
    deals: [
      { id: 'deal_101_1', title: 'CRM rollout pilot', amount: 42000, stage: 'Negotiation', closeDate: daysAgo(-14) },
    ],
    noteEntries: [
      { id: 'note_101_1', author: 'Sara Kim', body: 'High urgency. Wants decision before next budget cycle.', date: daysAgo(2) },
    ],
  },
  {
    id: 'cus_102',
    fullName: 'Daniel Morgan',
    email: 'daniel@bluepeakhealth.com',
    phone: '+1 (415) 555-0141',
    company: 'BluePeak Health',
    jobTitle: 'Operations Manager',
    status: 'Active',
    stage: 'Qualified',
    dealValue: 18500,
    notes: 'Strong fit for task automation and client relationship tracking across regional care teams.',
    createdAt: daysAgo(12),
    lastContactedAt: daysAgo(3),
    ownerId: 'usr_ethan',
    location: 'San Francisco, CA',
    industry: 'Healthcare',
    timeline: [
      {
        id: 'evt_102_1',
        type: 'Email',
        title: 'Inbound qualification',
        description: 'Customer requested a tailored demo focused on reporting.',
        date: daysAgo(10),
      },
      {
        id: 'evt_102_2',
        type: 'Call',
        title: 'Needs assessment',
        description: 'Mapped current workflows and pain points across service lines.',
        date: daysAgo(3),
      },
    ],
    deals: [{ id: 'deal_102_1', title: 'Regional team rollout', amount: 18500, stage: 'Qualified', closeDate: daysAgo(-24) }],
    noteEntries: [{ id: 'note_102_1', author: 'Ethan Cole', body: 'Needs integration notes for existing intake tools.', date: daysAgo(3) }],
  },
  {
    id: 'cus_103',
    fullName: 'Leah Thompson',
    email: 'leah@brightwellmedia.com',
    phone: '+1 (646) 555-0191',
    company: 'Brightwell Media',
    jobTitle: 'Revenue Lead',
    status: 'New',
    stage: 'Lead',
    dealValue: 9600,
    notes: 'New inbound lead from comparison page. Interested in pipeline dashboards and custom views.',
    createdAt: daysAgo(2),
    lastContactedAt: daysAgo(2),
    ownerId: 'usr_sara',
    location: 'New York, NY',
    industry: 'Media',
    timeline: [
      {
        id: 'evt_103_1',
        type: 'Email',
        title: 'Inbound request received',
        description: 'Lead asked for a quick overview of reporting capabilities.',
        date: daysAgo(2),
      },
    ],
    deals: [{ id: 'deal_103_1', title: 'Starter plan evaluation', amount: 9600, stage: 'Lead', closeDate: daysAgo(-18) }],
    noteEntries: [{ id: 'note_103_1', author: 'Sara Kim', body: 'Follow up with benchmark deck on Monday.', date: daysAgo(1) }],
  },
  {
    id: 'cus_104',
    fullName: 'Noah Brooks',
    email: 'noah@arklinelegal.com',
    phone: '+1 (404) 555-0128',
    company: 'Arkline Legal',
    jobTitle: 'Firm Administrator',
    status: 'Active',
    stage: 'Proposal',
    dealValue: 26500,
    notes: 'Evaluating CRM for intake, nurture sequences, and renewals. Needs stakeholder-friendly dashboards.',
    createdAt: daysAgo(21),
    lastContactedAt: daysAgo(5),
    ownerId: 'usr_admin',
    location: 'Atlanta, GA',
    industry: 'Legal',
    timeline: [
      {
        id: 'evt_104_1',
        type: 'Meeting',
        title: 'Live product walkthrough',
        description: 'Showed admin permissions, notes, and deal tracking.',
        date: daysAgo(16),
      },
      {
        id: 'evt_104_2',
        type: 'Email',
        title: 'Proposal sent',
        description: 'Sent seat breakdown, onboarding package, and service options.',
        date: daysAgo(5),
      },
    ],
    deals: [{ id: 'deal_104_1', title: 'Firm-wide adoption', amount: 26500, stage: 'Proposal', closeDate: daysAgo(-12) }],
    noteEntries: [{ id: 'note_104_1', author: 'Ariana Wells', body: 'Decision group includes finance and a senior partner.', date: daysAgo(5) }],
  },
  {
    id: 'cus_105',
    fullName: 'Sophia Nguyen',
    email: 'sophia@cinderlabs.ai',
    phone: '+1 (206) 555-0110',
    company: 'Cinder Labs',
    jobTitle: 'VP Partnerships',
    status: 'VIP',
    stage: 'Won',
    dealValue: 61000,
    notes: 'Closed enterprise deal with phased onboarding and executive business review cadence.',
    createdAt: daysAgo(41),
    lastContactedAt: daysAgo(4),
    ownerId: 'usr_admin',
    location: 'Seattle, WA',
    industry: 'Software',
    timeline: [
      {
        id: 'evt_105_1',
        type: 'Meeting',
        title: 'Contract signature',
        description: 'Closed annual agreement with multi-workspace package.',
        date: daysAgo(8),
      },
      {
        id: 'evt_105_2',
        type: 'Call',
        title: 'Onboarding kickoff',
        description: 'Defined success plan and internal stakeholders.',
        date: daysAgo(4),
      },
    ],
    deals: [{ id: 'deal_105_1', title: 'Enterprise workspace rollout', amount: 61000, stage: 'Won', closeDate: daysAgo(8) }],
    noteEntries: [{ id: 'note_105_1', author: 'Ariana Wells', body: 'Flag for QBR template and executive sponsor follow-up.', date: daysAgo(4) }],
  },
  {
    id: 'cus_106',
    fullName: 'James Foster',
    email: 'james@solsticefreight.com',
    phone: '+1 (713) 555-0154',
    company: 'Solstice Freight',
    jobTitle: 'Commercial Lead',
    status: 'Inactive',
    stage: 'Lost',
    dealValue: 15800,
    notes: 'Chose incumbent provider. Keep in nurture for Q3 revisit once contract window reopens.',
    createdAt: daysAgo(54),
    lastContactedAt: daysAgo(19),
    ownerId: 'usr_sara',
    location: 'Houston, TX',
    industry: 'Logistics',
    timeline: [
      {
        id: 'evt_106_1',
        type: 'Email',
        title: 'Decision update',
        description: 'Prospect delayed switch due to vendor lock-in.',
        date: daysAgo(19),
      },
    ],
    deals: [{ id: 'deal_106_1', title: 'Dispatcher workflow upgrade', amount: 15800, stage: 'Lost', closeDate: daysAgo(19) }],
    noteEntries: [{ id: 'note_106_1', author: 'Sara Kim', body: 'Schedule reactivation campaign in late summer.', date: daysAgo(18) }],
  },
  {
    id: 'cus_107',
    fullName: 'Emma Rivera',
    email: 'emma@havenretail.co',
    phone: '+1 (602) 555-0182',
    company: 'Haven Retail',
    jobTitle: 'Director of Customer Ops',
    status: 'Active',
    stage: 'Negotiation',
    dealValue: 33750,
    notes: 'Interested in centralizing store lead flow and service escalations into one reporting layer.',
    createdAt: daysAgo(7),
    lastContactedAt: daysAgo(1),
    ownerId: 'usr_ethan',
    location: 'Phoenix, AZ',
    industry: 'Retail',
    timeline: [
      {
        id: 'evt_107_1',
        type: 'Call',
        title: 'ROI review',
        description: 'Reviewed staffing gains from consolidating CRM workflows.',
        date: daysAgo(1),
      },
      {
        id: 'evt_107_2',
        type: 'Email',
        title: 'Pricing follow-up',
        description: 'Shared updated proposal with support tier comparison.',
        date: daysAgo(1),
      },
    ],
    deals: [{ id: 'deal_107_1', title: 'Regional retail operations suite', amount: 33750, stage: 'Negotiation', closeDate: daysAgo(-10) }],
    noteEntries: [{ id: 'note_107_1', author: 'Ethan Cole', body: 'Competitive deal. Response time matters.', date: daysAgo(1) }],
  },
  {
    id: 'cus_108',
    fullName: 'Lucas Bennett',
    email: 'lucas@monarchenergy.com',
    phone: '+1 (303) 555-0147',
    company: 'Monarch Energy',
    jobTitle: 'Regional Sales Director',
    status: 'Active',
    stage: 'Qualified',
    dealValue: 28700,
    notes: 'Needs visibility across distributed reps and a cleaner handoff between sales and onboarding.',
    createdAt: daysAgo(15),
    lastContactedAt: daysAgo(6),
    ownerId: 'usr_admin',
    location: 'Denver, CO',
    industry: 'Energy',
    timeline: [
      {
        id: 'evt_108_1',
        type: 'Meeting',
        title: 'Stakeholder alignment',
        description: 'Confirmed dashboard and role-based permission requirements.',
        date: daysAgo(6),
      },
    ],
    deals: [{ id: 'deal_108_1', title: 'Sales workflow modernization', amount: 28700, stage: 'Qualified', closeDate: daysAgo(-16) }],
    noteEntries: [{ id: 'note_108_1', author: 'Ariana Wells', body: 'Strong multiteam use case, but needs procurement timing.', date: daysAgo(6) }],
  },
  {
    id: 'cus_109',
    fullName: 'Charlotte Reed',
    email: 'charlotte@fablecapital.com',
    phone: '+1 (617) 555-0106',
    company: 'Fable Capital',
    jobTitle: 'Investor Relations Manager',
    status: 'New',
    stage: 'Lead',
    dealValue: 12400,
    notes: 'Requested a concise executive overview. Interested in premium reporting and activity history.',
    createdAt: daysAgo(1),
    lastContactedAt: daysAgo(1),
    ownerId: 'usr_sara',
    location: 'Boston, MA',
    industry: 'Finance',
    timeline: [
      {
        id: 'evt_109_1',
        type: 'Email',
        title: 'Inbound benchmark request',
        description: 'Asked for examples of investor communication workflows.',
        date: daysAgo(1),
      },
    ],
    deals: [{ id: 'deal_109_1', title: 'IR workflow pilot', amount: 12400, stage: 'Lead', closeDate: daysAgo(-21) }],
    noteEntries: [{ id: 'note_109_1', author: 'Sara Kim', body: 'Prepare polished one-page summary before demo scheduling.', date: daysAgo(1) }],
  },
  {
    id: 'cus_110',
    fullName: 'Aiden Brooks',
    email: 'aiden@verdantbuild.com',
    phone: '+1 (305) 555-0175',
    company: 'Verdant Build',
    jobTitle: 'Business Development Director',
    status: 'Active',
    stage: 'Proposal',
    dealValue: 22900,
    notes: 'Needs lead management and account visibility for project-based teams across multiple regions.',
    createdAt: daysAgo(28),
    lastContactedAt: daysAgo(9),
    ownerId: 'usr_ethan',
    location: 'Miami, FL',
    industry: 'Construction',
    timeline: [
      {
        id: 'evt_110_1',
        type: 'Call',
        title: 'Proposal scope review',
        description: 'Discussed onboarding package, reporting needs, and migration support.',
        date: daysAgo(9),
      },
    ],
    deals: [{ id: 'deal_110_1', title: 'Project account management package', amount: 22900, stage: 'Proposal', closeDate: daysAgo(-7) }],
    noteEntries: [{ id: 'note_110_1', author: 'Ethan Cole', body: 'Procurement requires polished business case before sign-off.', date: daysAgo(9) }],
  },
];

export const seedTasks = [
  { id: 'tsk_1', title: 'Prepare Northforge security recap', dueDate: daysAgo(-1), priority: 'High', completed: false },
  { id: 'tsk_2', title: 'Review BluePeak workflow notes', dueDate: daysAgo(0), priority: 'Medium', completed: false },
  { id: 'tsk_3', title: 'Update Cinder Labs onboarding checklist', dueDate: daysAgo(-3), priority: 'Low', completed: true },
];

export const seedNotifications = [
  {
    id: 'ntf_1',
    title: 'Quarterly forecast updated',
    message: 'Pipeline value increased 12% after this week\'s proposal activity.',
    createdAt: daysAgo(0),
  },
  {
    id: 'ntf_2',
    title: 'Northforge moved to negotiation',
    message: 'Security review is underway and pricing is under procurement review.',
    createdAt: daysAgo(1),
  },
  {
    id: 'ntf_3',
    title: 'Admin reminder',
    message: 'Two users still need role review and access confirmation.',
    createdAt: daysAgo(2),
  },
];
