import { BookOpen, CheckCircle2, Clock3, LifeBuoy, Mail, MessageSquare, Search } from 'lucide-react';
import { useContext, useState } from 'react';
import Button from '../../components/ui/Button';
import Card from '../../components/ui/Card';
import Badge from '../../components/ui/Badge';
import { UIContext } from '../../context/UIContext';
import { addActivityEntry, addNotification } from '../../services/storage';

const faqItems = [
  {
    title: 'How do I import customers?',
    description: 'Use Accounts > Add Customer for single records. CSV import is handled through a guided support workflow.',
  },
  {
    title: 'Can I change pipeline stages?',
    description: 'Yes. Workspace admins can configure default stages from Settings and apply them to new records.',
  },
  {
    title: 'Where do notifications come from?',
    description: 'Notifications are generated by CRM actions, account updates, support activity, and workspace status checks.',
  },
];

const docs = [
  ['Getting started guide', 'Set up your workspace, users, and first account.'],
  ['Pipeline playbook', 'Learn recommended CRM stages and forecasting practices.'],
  ['Admin controls', 'Manage team access, workspace preferences, and security.'],
];

const tickets = [
  ['#SUP-1042', 'CSV import mapping review', 'Waiting on customer', 'warning'],
  ['#SUP-1038', 'Pipeline forecast export', 'Resolved', 'success'],
  ['#SUP-1029', 'Workspace onboarding call', 'Scheduled', 'brand'],
];

function SupportPage() {
  const { showToast } = useContext(UIContext);
  const [query, setQuery] = useState('');

  function contactSupport() {
    addActivityEntry({
      title: 'Support request created',
      description: 'A new support request was opened from the help center.',
    });
    addNotification({
      title: 'Support request received',
      message: 'The Controllusion team will respond within the current SLA window.',
      path: '/support',
    });
    showToast({
      title: 'Support request created',
      description: 'We added a support ticket to your workspace timeline.',
    });
  }

  function openDoc(title) {
    addNotification({
      title: 'Documentation opened',
      message: `${title} was added to your recent help resources.`,
      path: '/support',
    });
    showToast({
      title,
      description: 'Documentation preview opened in the help center.',
      type: 'info',
    });
  }

  const filteredFaqs = faqItems.filter((item) =>
    [item.title, item.description].join(' ').toLowerCase().includes(query.trim().toLowerCase()),
  );

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <h1 className="text-[24px] font-black tracking-[-0.05em] text-[#14213d]">Support Center</h1>
          <p className="mt-1 text-[12px] font-medium text-[#52627b]">Find answers, review support status, and contact the Controllusion team.</p>
        </div>
        <Button onClick={contactSupport}>
          <LifeBuoy className="h-3.5 w-3.5" />
          Contact Support
        </Button>
      </div>

      <div className="grid gap-5 xl:grid-cols-[1fr_300px]">
        <div className="space-y-5">
          <Card className="rounded-[9px] p-6">
            <div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between">
              <div className="flex gap-4">
                <span className="flex h-12 w-12 items-center justify-center rounded-[10px] bg-[#eef2ff] text-[#4c42e8]">
                  <LifeBuoy className="h-6 w-6" />
                </span>
                <div>
                  <h2 className="text-[18px] font-black tracking-[-0.04em] text-[#14213d]">Help center overview</h2>
                  <p className="mt-2 max-w-[560px] text-[12px] leading-6 text-[#52627b]">
                    Search common questions, open documentation, or create a support request. Your workspace activity and notifications update when support actions happen.
                  </p>
                </div>
              </div>
              <div className="relative w-full md:w-[260px]">
                <Search className="pointer-events-none absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-[#9aa8bf]" />
                <input
                  className="h-9 w-full rounded-[7px] bg-[#f3f7ff] pl-8 pr-3 text-[12px] outline-none"
                  onChange={(event) => setQuery(event.target.value)}
                  placeholder="Search help topics..."
                  value={query}
                />
              </div>
            </div>
          </Card>

          <div className="grid gap-4 md:grid-cols-3">
            {filteredFaqs.map((item) => (
              <Card className="rounded-[9px] p-5" key={item.title}>
                <MessageSquare className="h-5 w-5 text-[#4c42e8]" />
                <h3 className="mt-4 text-[14px] font-black text-[#14213d]">{item.title}</h3>
                <p className="mt-2 text-[11px] leading-5 text-[#52627b]">{item.description}</p>
              </Card>
            ))}
          </div>

          <Card className="rounded-[9px] p-6">
            <h2 className="text-[15px] font-black text-[#14213d]">Documentation & help links</h2>
            <div className="mt-5 grid gap-3">
              {docs.map(([title, description]) => (
                <button
                  className="flex items-center justify-between rounded-[8px] bg-[#f7f9ff] p-4 text-left hover:bg-[#eef4ff]"
                  key={title}
                  onClick={() => openDoc(title)}
                  type="button"
                >
                  <span className="flex items-center gap-3">
                    <BookOpen className="h-4 w-4 text-[#4c42e8]" />
                    <span>
                      <span className="block text-[12px] font-black text-[#14213d]">{title}</span>
                      <span className="mt-1 block text-[11px] text-[#70809a]">{description}</span>
                    </span>
                  </span>
                  <Badge variant="brand">Open</Badge>
                </button>
              ))}
            </div>
          </Card>
        </div>

        <div className="space-y-5">
          <Card className="rounded-[9px] bg-[#eef4ff] p-5">
            <div className="flex items-center gap-3">
              <CheckCircle2 className="h-5 w-5 text-[#2e8a5f]" />
              <div>
                <h2 className="text-[14px] font-black text-[#14213d]">Support status</h2>
                <p className="text-[11px] text-[#52627b]">All systems operational</p>
              </div>
            </div>
            <div className="mt-5 space-y-3 text-[11px]">
              {[
                ['First response', '< 2 hours'],
                ['Current SLA', '99.9%'],
                ['Open priority tickets', '0'],
              ].map(([label, value]) => (
                <div className="flex justify-between rounded-[7px] bg-white px-3 py-2" key={label}>
                  <span className="font-semibold text-[#52627b]">{label}</span>
                  <span className="font-black text-[#14213d]">{value}</span>
                </div>
              ))}
            </div>
          </Card>

          <Card className="rounded-[9px] p-5">
            <h2 className="text-[14px] font-black text-[#14213d]">Recent tickets</h2>
            <div className="mt-4 space-y-3">
              {tickets.map(([id, title, status, variant]) => (
                <div className="rounded-[8px] border border-[#edf2fb] p-3" key={id}>
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <p className="text-[11px] font-black text-[#14213d]">{title}</p>
                      <p className="mt-1 text-[10px] text-[#70809a]">{id}</p>
                    </div>
                    <Badge variant={variant}>{status}</Badge>
                  </div>
                </div>
              ))}
            </div>
          </Card>

          <Card className="rounded-[9px] p-5">
            <h2 className="text-[14px] font-black text-[#14213d]">Contact support</h2>
            <div className="mt-4 space-y-3 text-[11px] text-[#52627b]">
              <p className="flex items-center gap-2">
                <Mail className="h-4 w-4 text-[#4c42e8]" />
                support@controllusion.com
              </p>
              <p className="flex items-center gap-2">
                <Clock3 className="h-4 w-4 text-[#4c42e8]" />
                Mon-Fri, 8:00-18:00
              </p>
            </div>
          </Card>
        </div>
      </div>
    </div>
  );
}

export default SupportPage;
